# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 19:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160329_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='photo',
            field=models.TextField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_long',
            field=models.TextField(blank=True, null=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_short',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('B', 'Bachelor project'), ('M', "Master's project"), ('T', "Master's thesis"), ('C', 'Project with compay'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='fax',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
