# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_group_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
