# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 15:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('projects', '0001_initial'), ('projects', '0002_auto_20160329_1020'), ('projects', '0003_auto_20160411_2152'), ('projects', '0004_auto_20160411_2202'), ('projects', '0005_group_publication'), ('projects', '0006_group_website'), ('projects', '0007_group_subject')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[(b'B', b'Bachelor project'), (b'M', b"Master's project"), (b'T', b"Master's thesis"), (b'C', b'Project with compay'), (b'O', b'Other')], max_length=1)),
                ('subject', models.CharField(max_length=128)),
                ('description_short', models.CharField(blank=True, max_length=256, null=True)),
                ('description_long', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=128, null=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('website', models.URLField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('workplace', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('fax', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('photo', models.TextField(blank=True, max_length=33554432, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Supervisor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_long',
            field=models.TextField(blank=True, null=True, verbose_name=b'Long description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_short',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name=b'Short description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_long',
            field=models.TextField(blank=True, null=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_short',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('B', 'Bachelor project'), ('M', "Master's project"), ('T', "Master's thesis"), ('C', 'Project with compay'), ('O', 'Other')], max_length=1),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('members', models.ManyToManyField(to='projects.Supervisor')),
                ('website', models.URLField(blank=True, max_length=128, null=True)),
                ('subject', models.TextField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('description_short', models.TextField(blank=True, max_length=256, null=True)),
                ('description_long', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=128, null=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Supervisor')),
            ],
        ),
    ]
