# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description_long',
            field=models.TextField(blank=True, null=True, verbose_name=b'Long description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_short',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name=b'Short description'),
        ),
    ]
