# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160314_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='status',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='website',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='workplace',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
