# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160411_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='photo',
            field=models.TextField(blank=True, max_length=33554432, null=True),
        ),
    ]
