# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_group_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='website',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
