# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160315_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_long',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_short',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='subject',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='website',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
