# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160317_1236'),
        ('projects', '0009_auto_20160322_1208'),
    ]

    operations = [
    ]
