# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 10:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'project_stock', '0001_initial'), (b'project_stock', '0002_auto_20160428_0233'), (b'project_stock', '0003_supervisor_user'), (b'project_stock', '0004_auto_20160509_1011'), (b'project_stock', '0005_project_end_date'), (b'project_stock', '0006_auto_20160511_1246'), (b'project_stock', '0007_project_file_upload'), (b'project_stock', '0008_auto_20160525_1116'), (b'project_stock', '0009_auto_20160525_1119'), (b'project_stock', '0010_auto_20160525_1132'), (b'project_stock', '0011_auto_20160525_1142')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subject', models.TextField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('B', 'Bachelor project'), ('M', "Master's project"), ('T', "Master's thesis"), ('C', 'Project with compay'), ('O', 'Other')], max_length=1)),
                ('subject', models.CharField(max_length=128)),
                ('description_short', models.TextField(blank=True, max_length=256, null=True, verbose_name='Short description')),
                ('description_long', models.TextField(blank=True, null=True, verbose_name='Long description')),
                ('website', models.URLField(blank=True, max_length=128, null=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('description_short', models.TextField(blank=True, max_length=256, null=True)),
                ('description_long', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=128, null=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, default='', max_length=128)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('workplace', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(blank=True, default='', max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mobile', models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('fax', models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('photo', models.TextField(blank=True, default='', max_length=33554432)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_stock.Supervisor'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_stock.Supervisor'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to=b'project_stock.Supervisor'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.TextField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='group',
            name='website',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_long',
            field=models.TextField(blank=True, default='', verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_short',
            field=models.TextField(blank=True, default='', max_length=256, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subject',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_long',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_short',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='website',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='file_upload',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b'files/%Y/%m/%d'),
        ),
    ]
