# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 08:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_stock', '0003_supervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.TextField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='group',
            name='website',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_long',
            field=models.TextField(blank=True, default='', verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_short',
            field=models.TextField(blank=True, default='', max_length=256, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subject',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_long',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_short',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='website',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='photo',
            field=models.TextField(blank=True, default='', max_length=33554432),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='status',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='website',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='workplace',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
