# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_stock', '0005_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
