# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 13:07
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_stock', '0006_auto_20160511_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/stock/file/%Y/%m/%d')),
        ),
    ]
