# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_stock', '0009_auto_20160525_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=b'files/%Y/%m/%d'),
        ),
    ]
