# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_stock', '0011_auto_20160525_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_upload',
            field=models.FileField(blank=True, default='', null=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
