# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 10:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160314_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='tel',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='hej', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Supervisor'),
        ),
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
